services:
 postgres:
   container_name: postgres-container
   image: postgres:17
   environment:
     POSTGRES_DB: ${DATABASE_NAME}
     POSTGRES_USER: ${DATABASE_USERNAME}
     POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
   ports:
     - "1234:5432"
   volumes:
     - postgres_data:/var/lib/postgresql/data
   env_file:
     - .env
 
#  django:
#    build: .
#    container_name: django-container
#    ports:
#      - "8000:8000"
#    depends_on:
#      - postgres
#    environment:
#      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
#      DEBUG: ${DEBUG}
#      DJANGO_LOGLEVEL: ${DJANGO_LOGLEVEL}
#      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
#      DATABASE_ENGINE: ${DATABASE_ENGINE}
#      DATABASE_NAME: ${DATABASE_NAME}
#      DATABASE_USERNAME: ${DATABASE_USERNAME}
 
#      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
#      DATABASE_HOST: ${DATABASE_HOST}
#      DATABASE_PORT: ${DATABASE_PORT}
#    env_file:
#      - .env

 rabbitmq:
    restart: always
    image: rabbitmq:latest
    container_name: rabbitmq-container
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"
    environment:
      RABBITMQ_DEFAULT_VHOST: "/"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

 pgadmin:
    container_name: pgadmin-container
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    restart: unless-stopped

volumes:
   postgres_data: